export interface GitHubConfig {
  token: string;
  templateOwner: string;
  templateRepo: string;
}

export class GitHubService {
  constructor(private config: GitHubConfig) {}

  /**
   * Chiama POST /repos/{templateOwner}/{templateRepo}/generate e ritorna subito repoData.
   * NON attende che il repo sia disponibile — usare waitForRepo per quello.
   * Il chiamante può aggiornare D1 tra createRepoFromTemplate e waitForRepo (D-10 idempotency).
   */
  async createRepoFromTemplate(
    name: string,
    description?: string
  ): Promise<any> {
    const response = await fetch(
      `https://api.github.com/repos/${this.config.templateOwner}/${this.config.templateRepo}/generate`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.config.token}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
          'User-Agent': 'Rank-and-Rent-Factory-Core',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          owner: this.config.templateOwner,
          name,
          description: description ?? '',
          private: false,
        }),
      }
    );

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`GitHub template generate error: ${response.status} ${error}`);
    }

    return await response.json();
  }

  /**
   * Retry loop: interroga GET /repos/{owner}/{repo} fino a maxAttempts volte
   * con intervallo intervalMs tra i tentativi.
   * Lancia Error se il repo non è disponibile entro i tentativi consentiti.
   * NOTA: il token NON viene mai incluso nei messaggi di errore (T-04-03-02).
   */
  async waitForRepo(
    owner: string,
    repo: string,
    maxAttempts: number = 10,
    intervalMs: number = 500
  ): Promise<void> {
    for (let i = 0; i < maxAttempts; i++) {
      const res = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
        headers: {
          'Authorization': `Bearer ${this.config.token}`,
          'Accept': 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
          'User-Agent': 'Rank-and-Rent-Factory-Core',
        },
      });
      if (res.ok) return;
      await new Promise(resolve => setTimeout(resolve, intervalMs));
    }
    throw new Error(`GitHub repo ${owner}/${repo} not ready after ${maxAttempts} attempts`);
  }

  /**
   * Backward-compat: crea il repo da template e aspetta che sia disponibile.
   * Il chiamante 04-05 usa createRepoFromTemplate + waitForRepo separati per
   * poter aggiornare D1 tra i due step (idempotency D-10).
   */
  async createProjectRepo(name: string, description: string = 'Generated by Rank and Rent Factory') {
    const repoData = await this.createRepoFromTemplate(name, description);
    const repoOwner = (repoData as any).owner?.login ?? this.config.templateOwner;
    const repoName = (repoData as any).name ?? name;
    await this.waitForRepo(repoOwner, repoName);
    return repoData;
  }

  async createFile(owner: string, repo: string, path: string, content: string, message: string = 'Add configuration') {
    const url = `https://api.github.com/repos/${owner}/${repo}/contents/${path}`;

    const response = await fetch(url, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${this.config.token}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'Rank-and-Rent-Factory-Core',
      },
      body: JSON.stringify({
        message,
        content: btoa(content), // GitHub API requires base64 content
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`GitHub API error (createFile): ${response.status} ${error}`);
    }

    return await response.json();
  }
}
