export interface GitHubConfig {
  token: string;
  templateOwner: string;
  templateRepo: string;
}

export class GitHubService {
  constructor(private config: GitHubConfig) {}

  async createProjectRepo(name: string, description: string = 'Generated by Rank and Rent Factory') {
    const url = `https://api.github.com/repos/${this.config.templateOwner}/${this.config.templateRepo}/generate`;
    
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${this.config.token}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'Rank-and-Rent-Factory-Core'
      },
      body: JSON.stringify({
        name,
        description,
        include_all_branches: false,
        private: true
      })
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`GitHub API error: ${response.status} ${error}`);
    }

    return await response.json();
  }

  async createFile(owner: string, repo: string, path: string, content: string, message: string = 'Add configuration') {
    const url = `https://api.github.com/repos/${owner}/${repo}/contents/${path}`;
    
    const response = await fetch(url, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${this.config.token}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'Rank-and-Rent-Factory-Core'
      },
      body: JSON.stringify({
        message,
        content: btoa(content) // GitHub API requires base64 content
      })
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`GitHub API error (createFile): ${response.status} ${error}`);
    }

    return await response.json();
  }
}
